[mongo]
uri = "mongodb+srv://mudita_test:IM2LJDtwcNJWboAK@varshatest1.6wiorhk.mongodb.net/?retryWrites=true&w=majority&appName=Varshatest1"

[credentials.usernames.kpadman]
email = "kanchana_16@yahoo.com"
name = "kpadman"
password = "$2b$12$Eh2j3JNf3KyBVZimrm0zR.uO8Bn7SAxEJ4o9X4ly5XaNrT4mrmxd6"

#[credentials]
#	[credentials.usernames]
#		[credentials.usernames.kpadman]
#			name = "kpadman"
#			password = "$2b$12$Eh2j3JNf3KyBVZimrm0zR.uO8Bn7SAxEJ4o9X4ly5XaNrT4mrmxd6"
#		[credentials.usernames.svas]
#			name = "svas"
#			password = "$2b$12$Eh2j3JNf3KyBVZimrm0zR.uO8Bn7SAxEJ4o9X4ly5XaNrT4mrmxd6"

[cookie]
expiry_days = 30
key = "random_signature_key"
name = "random_cookie_name"
